import { motion } from "framer-motion";
import { Container } from "@/components/primitives/Container";
import { SectionHeader } from "@/components/primitives/SectionHeader";
import { ChartFigure } from "@/components/features/charts/ChartFigure";
import { BarsCompare } from "@/components/features/charts/BarsCompare";
import { Stat } from "@/components/primitives/Stat";
import { WASTE_CATEGORIES } from "@/data/emissions";
import { fadeRise } from "@/lib/motion";

/** WasteSection — circularity narrative + verified category data. */
export function WasteSection() {
  const w = WASTE_CATEGORIES;
  return (
    <section aria-label="Waste management" className="py-section md:py-section-lg" id="waste">
      <Container>
        <SectionHeader
          overline="Waste management"
          title="Circularity as an operating habit."
          lead="As an office-based enterprise our streams are e-waste, paper, plastics, packaging and organics — managed for segregation, reuse, and compliant disposal through authorized recyclers."
        />

        <div className="grid gap-6 lg:grid-cols-12">
          <div className="lg:col-span-7">
            <ChartFigure
              title="Waste by category, YoY"
              summary={`${w.totalFy25} tonnes generated in FY2024–25; ${w.diversionPct}% diverted from landfill through recycling, reuse and composting.`}
              source={w.source}
              table={{
                caption: "Waste generated by category (tonnes)",
                headers: ["Category", "FY2023–24", "FY2024–25"],
                rows: w.rows.map((r) => [r.category, r.fy24, r.fy25]),
              }}
            >
              <BarsCompare
                rows={w.rows.map((r) => ({ label: r.category, a: r.fy24, b: r.fy25 }))}
                seriesLabels={["FY2023–24", "FY2024–25"]}
                format={(v) => `${v.toLocaleString()} t`}
              />
            </ChartFigure>
          </div>

          <motion.div
            className="flex flex-col justify-center gap-10 lg:col-span-5"
            variants={fadeRise}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
          >
            <Stat
              value={w.diversionPct}
              suffix="%"
              decimals={1}
              label="of waste diverted from landfill"
              pillar="environment"
              size="m"
            />
            <Stat
              value={w.plasticsEliminatedT}
              suffix=" t"
              decimals={1}
              label="plastics eliminated or recycled"
              pillar="environment"
              size="s"
            />
            <div className="text-body text-ink">
              <p>
                End-of-life IT assets are routed exclusively to government-authorized e-waste
                recyclers under India's E-Waste (Management) Rules, 2022 — and equipment with
                life left is donated to underserved school systems, extending usefulness while
                advancing digital equity.
              </p>
              <p className="mt-3 text-body-s text-neutral-500">
                Disposition FY2024–25: {w.disposition.recycledPct}% recycled ·{" "}
                {w.disposition.compostedPct}% composted · {w.disposition.landfillPct}% landfilled
                via municipal systems.
              </p>
            </div>
          </motion.div>
        </div>
      </Container>
    </section>
  );
}
